### ISSUE TITLE
Blog on React JS

### ISSUE THREAD

**Issue by gdscpce** [gdscpce/hacktober-blog#4]
Write a short informative blog on React JS and also provide some code snippet to understand its Syntax.

1) Follow and Read Contributing Guidelines.
2) Only the assigned person is allowed to raise the PR on this Issue
3) To get this issue assigned to you comment on this issue

**Comment by Shivraj-Nakum** [comment]
Can i work on this , assign it to me i would be happy to contribute

**Comment by bhavanamn** [comment]
please assign this blog to me:
NAME: M N BHAVANA
CLASS :TY COMPS
COLLEGE:PCE

**Comment by nishaaannnt** [comment]
go for it @bhavanamn
