### ISSUE TITLE
Blog on Tree Data Structure

### ISSUE THREAD

**Issue by gdscpce** [gdscpce/hacktober-blog#9]
Write a short informative blog on Tree Data Structure and also provide some code snippet to understand it.

1) Follow and Read Contributing Guidelines.
2) Only the assigned person is allowed to raise the PR on this Issue
3) To get this issue assigned to you comment on this issue

**Comment by KESHAV4R3** [comment]
hii @gdscpce please assign this issue to me as it seems to be fit for my domain ....

**Comment by prernads** [comment]
hii @gdscpce please assign me this blog.

**Comment by nishaaannnt** [comment]
Go for it @prernads
